const quotes = {
    motivation: ['You’re not stuck. You’re just scared of the work required to be free.', 'You didn’t run out of time. You wasted it.', 
        'You crave comfort more than you crave change — and it shows.', "You aren't unlucky — you're undisciplined.", 
        'Success isn’t hiding from you. You’re hiding from effort.', 'You’re not exhausted. You’re uninspired.', 
        'Most people don’t fail. They quit and call it fate.', 'Your future is dying in the hands of your excuses.', 
        'You have 24 hours like everyone else — stop acting like you don’t.', 'Nothing will change until you hate your own laziness more than you fear failure.'
        , 'Life isn’t short. You just waste too much of it.', 'You’re broke because you spend more than you build — time, money, energy.', 
        'If you don’t sacrifice for your goals, your goals become the sacrifice.', 'You want the reward without the responsibility. That’s delusion.', 
        'Every excuse you use is a brick in the wall between you and your potential.', 'You keep blaming the world when it’s your own reflection that’s in the way.', 
        'No one owes you understanding. Not even life.', "The truth is: you don't want it bad enough.", 'You said you were grinding, but Netflix heard otherwise.', 
        "You're not too late — you're just too soft.", 'You don’t have writer’s block. You have cowardice masked as perfectionism.', 
        'You chose scrolling over building. Now you’re behind.', 'You’re scared to try because failure would prove you’ve been wasting time.', 
        "You're not overwhelmed. You're undisciplined.", 'Winners bleed too — they just don’t stop when it hurts.', 'You want results, but not enough to change your habits.', 
        'Your mind isn’t your prison — your comfort is.', 'Your life is a reflection of what you allow, not what you want.', 'You’ve been lied to — motivation isn’t magic, it’s muscle.', 
        "If you don't get uncomfortable now, life will make you uncomfortable later.", 'You’re not tired — you’re just used to quitting.', 'You think you need a break? Try earning it first.', 
        'If you’re still explaining, you’re not executing.', 'Your dreams are suffocating under your distractions.', 'Your actions scream louder than your intentions ever will.', 
        'You don’t get to complain about results you didn’t earn.', 'You’re not behind. You just keep choosing the easy way.', 'Most people choose a slow death over disciplined life.', 
        'You’re killing time. And time is sharpening the knife.', 'You said you were committed. Then came temptation — and you folded.', 
        'You gave up on yourself the moment it got uncomfortable.', 'Your phone knows you better than your goals do.', 'The truth hurts — which is why you avoid it.', 
        'Your story isn’t inspiring yet because you’re still in the excuses chapter.', 'Hard truth: No one’s thinking about you as much as you think.',
        'You’re addicted to comfort, and withdrawal looks like progress.', 'Don’t fear failure. Fear never trying at all.', 
        'You want the dream life with minimum struggle — that’s called fantasy.', 'You’ve got a plan B because you don’t believe in plan A.', 
        'You procrastinate because deep down you don’t believe you’ll succeed.', 'Stop expecting growth in soil you keep poisoning.',
        'Nobody cares how hard it is — just if it gets done.', "You're not being held back. You're holding yourself hostage.", 
        "If your effort matched your complaints, you'd already be there.", 'You treat your goals like chores, then wonder why they don’t come true.', 
        'You say you want it, but your habits call that a lie.', 'Dreams die in comfort zones.', 'If you don’t fight for it, prepare to envy someone who did.', 
        "You get one shot at this life. And you're wasting it scrolling.", 'Your emotions are not an excuse for inaction.', 
        'Your reputation is built on what you tolerate in yourself.', 'Most people aren’t unlucky. They’re undisciplined.', 
        'You weren’t born behind. You fell behind by choosing easy.', 'There’s no such thing as staying the same. You’re either growing or decaying.', 
        'Every minute you waste is a minute your future self will resent you for.', 'Your fear of discomfort is stronger than your desire to succeed.', 
        'You’re not misunderstood. You’re underachieving.', 'You say you’re stuck. No — you stopped climbing.', 'You can have excuses or results — not both.', 
        'The time you waste justifies the failure you fear.', 'It’s not that you lack time. You just lack priority.', 
        'That plan you never started? Someone else did. And they’re winning.', 'Stop blaming the system when you haven’t mastered yourself.', 
        'You’re burning daylight building nothing.', 'The grind doesn’t care how you feel today.', 'You keep playing victim to your own habits.',
        'Your comfort is costing your greatness.', 'You want applause for effort. The world only rewards results.', 
        'You’re not ‘figuring it out.’ You’re just avoiding the work.', 'Most people sleepwalk through life, and you might be one of them.',
        'You don’t fear failure. You fear exposure.', 'That pain you avoid? It’s the door to your next level.', 'The clock is still ticking — whether you move or not.',
        "One day you'll wish you started today.", 'Excuses are lies dressed in reasons.', 'You’re not a perfectionist. You’re a procrastinator with better branding.', 
        'Most people choose regret over resilience.', 'Stop romanticizing struggle. Fight through it or be defined by it.', 
        'You keep making promises to yourself and breaking every one.', 'If your goals aren’t worth the pain, they weren’t real to begin with.', 
        'You weren’t rejected. You were revealed.', 'Quit calling yourself unlucky. You’re just undisciplined.', 
        'Your goals are starving while you binge on distractions.', 'Self-pity burns time and builds nothing.', 
        'You’re waiting for the perfect moment that will never come.', 'If you’re tired of starting over, stop quitting.', 
        'You want to be remembered, but you live like you’re invisible.', 'You’re not too busy — you’re just uncommitted.', 
        'The grind is lonely — but so is regret.', 'You’re scared of what you’d become if you actually tried.', 
        'You’re not waiting for the right moment — you’re avoiding responsibility.', 'Your ‘overthinking’ is just fear wearing a crown.', 
        'You keep rehearsing your downfall and calling it preparation.', 'Every day you delay is a deal you make with mediocrity.', 
        'You’re haunted by your potential because you keep betraying it.', 'Discipline isn’t punishment — it’s self-respect.', 
        'If you won’t fight for your future, who will?', 'Comfort is the silent killer of ambition.', 'The longer you wait, the heavier your regret will get.',
        'You don’t need more time. You need fewer lies to yourself.', 'You either control your mind, or it controls your fate.', 
        'You’ve built a routine around avoidance and called it peace.', 'That voice telling you to ‘wait’ is fear disguised as logic.', 
        'Every day is a choice — build or decay.', 'If your habits were a person, you’d block them.', 'You’re running from a version of you that could’ve changed everything.', 
        'You aren’t lost — you’re just scared of what you’d find if you actually looked.', "You don't need permission to stop being average.", 
        'That thing you’re ‘thinking about doing’ is the one that will free you.', 'You are the villain in your own progress story.', 
        'Your pain won’t disappear — it just accumulates until it explodes.', 'Most people don’t change — they just become more efficient at avoiding growth.', 
        'You’re not chasing your dream. You’re negotiating your fear.', 'You want clarity? Act. Clarity follows action.', 
        'You haven’t hit rock bottom — you’ve just gotten too good at tolerating pain.', 'Your anxiety is just energy with no mission.', 
        'If you always need motivation, you’ve already lost.', 'Your future is suffocating under your current comfort.', 
        'You’re building a life around what you tolerate — not what you want.', 'You’re dying in slow motion — and calling it stability.', 
        'Your standards shape your suffering.', 'Most of your problems are symptoms of inaction.', 
        'You don’t need therapy. You need to keep the promises you made to yourself.', "You can't grow if you're busy protecting your ego.", 
        'Self-sabotage is just self-preservation dressed in panic.', "You aren't behind. You're just still negotiating with your demons.", 
        "If you don't face your darkness, it will drive your decisions.", 'Want peace? Earn it through execution.', 
        'The only person who needs to believe in you... is the one in the mirror.', 'You know what to do. You’re just scared it will actually change you.', 
        'Everything you avoid owns you.', 'Every easy choice you make now adds weight to your future.', 
        'You fear failure — but you should fear wasted potential more.', "You're not mentally tired. You're spiritually starved.", 
        'You are one brutal truth away from a breakthrough.', 'You’re not confused. You’re just hoping you don’t have to try.', 
        'You don’t need confidence. You need courage. Confidence comes later.', 'What if your greatest self is waiting on the other side of discomfort?', 
        'You’re overcomplicating progress to avoid committing to it.', 'Silence the noise. You already know the answer.', 
        'Your future self is watching everything you’re doing right now — silently judging.', 'Don’t just survive the storm. Become it.', 
        "If your life feels meaningless, maybe it's time to give it one.", 'That ‘someday’ you’re waiting for is already running late.', 
        "You're not addicted to comfort — you're enslaved by it.", 'You say you want to evolve, but you still cling to your excuses like lifelines.', 
        "If you don't master your emotions, they will master your direction.", 'There’s no ‘next level’ if you can’t survive this one.', 
        'Procrastination is choosing failure by default.', 'You’ve buried your goals under a blanket of distractions.', 
        'You’re not stuck — you just haven’t suffered enough to move.', 'You’re scared to heal because you’ve built an identity around pain.', 
        'You won’t find peace by avoiding the war inside you.', "Growth isn't found in comfort. It's hidden in confrontation.", 
        'You know what’s killing your potential. You just keep petting it.', 'Your internal chaos is a reflection of every dream you’ve abandoned.', 
        'You’re not bored. You’re avoiding becoming who you were meant to be.', 'You want peace but keep choosing habits that destroy it.', 
        'That inner voice whispering ‘more’ is your true self screaming.', 'Stop chasing motivation. Start building momentum.', 
        'You’re the architect of your hell — and the only one who can burn it down.', 'Most people fear success more than failure. Don’t be most people.', 
        'You’re not a late bloomer. You’re just still procrastinating.', "You don't fear failure. You fear being seen trying and still not winning.", 
        'Every excuse is a slow funeral for your dreams.', 'You’ve mastered comfort. Now master the consequences.', 'You’ll never be ‘ready.’ You’re already overdue.', 
        'Rock bottom isn’t punishment. It’s permission to restart.', 'You didn’t fail. You avoided the fight.', 'You’re not avoiding burnout. You’re avoiding commitment.', 
        "Discipline is remembering what you said you'd do — long after the mood has left.", 'Your timeline is a myth. Move now.', 'If your life was a movie, would you be the hero — or the excuse?', 
        'Every distraction is a thief disguised as entertainment.', 'You’re addicted to starting and allergic to finishing.', 'You won’t level up until your rituals do.', 
        'There is no transformation without friction.', 'Change feels like death — but so does staying the same.', 'You won’t become who you want by being who you are.', 
        'That feeling you call anxiety is your potential pacing in a cage.', 'Be careful — comfort can feel a lot like happiness until it traps you.', 
        'You don’t need answers. You need action.', 'What you avoid becomes your master.', 'The truth you’re dodging is the truth that will set you free.', 
        'Your dream life is hiding behind the work you keep avoiding.', 'The worst kind of pain? Knowing you could’ve done more.', 'Your current mindset is the ceiling to your entire existence.',
        'Don’t wait for rock bottom — build a launchpad now.', 'You’re not the same person you were — so stop acting like it.', 'There is no next chapter until you finish this one.'],
    depressed: [
        "You’re not waiting for the right moment — you’re avoiding the hard truth.",
        "Your comfort is your cage. It just has nice cushions.",
        "The longer you sit in silence, the louder your mind gets — and it rarely says kind things.",
        "No one is coming to fix your life. They’re too busy pretending theirs is fine.",
        "You’re not broken. You’re just using survival skills in a life that demands living.",
        "Pain doesn’t build character. Choices made in pain do.",
        "If you won’t rescue yourself, don’t expect the world to care.",
        "You weren’t born to suffer. But if you never move, suffering becomes home.",
        "Your mind is a weapon. And right now, it’s aimed at you.",
        "You fear failure more than you hate this misery. That’s why you’re stuck.",
        "You don’t need motivation — you need consequences.",
        "If your routine numbs you, it’s not routine. It’s rot.",
        "Every excuse you make is a small funeral for potential.",
        "Self-pity feels warm, but it will rot you from within.",
        "You're not tired. You're unfulfilled, underused, and quietly screaming.",
        "The person you are when no one’s watching — that’s the one dragging you down.",
        "Your demons don’t hide in shadows. They live in your habits.",
        "Most people aren't lazy — they're afraid. But fear wears many masks.",
        "You survived worse than this. The only difference now is you stopped fighting.",
        "People don’t notice your pain because you trained them not to.",
        "You don’t lack time. You waste it pretending you have more.",
        "There’s no peace in avoidance. Only delay and decay.",
        "Your greatest enemy isn't depression — it's your refusal to confront it.",
        "You’re not alone. You’re surrounded by people hiding the same darkness.",
        "A numb soul isn’t calm. It’s a warning sign.",
        "You can’t heal in a place you keep relapsing in.",
        "Depression is a liar — but it’s very convincing when you’re silent.",
        "Your life won’t change if your habits don’t.",
        "What you tolerate becomes your identity.",
        "You don’t want to die. You want to stop hurting — there’s a difference.",
        "Nobody sees your silent battles, but you feel every cut.",
        "If you can’t win the war, win today. Then win again tomorrow.",
        "Rock bottom isn't a location. It's a decision point.",
        "Your sadness doesn’t make you deep. What you do with it does.",
        "Suffering for no reason isn’t noble. It’s neglect.",
        "You either become the hero of your story or the ghost in someone else’s.",
        "You can blame the world, but it won’t give you a refund.",
        "The mirror never lies. That’s why you avoid it.",
        "You can keep breaking or start building. Choose your cycle.",
        "Hope without action is just a hallucination.",
        "If you don't respect yourself, don’t expect others to.",
        "You are not your trauma. You are what you build from it.",
        "The world owes you nothing. And that’s your greatest freedom.",
        "You can’t fix your life with the same mindset that broke it.",
        "Darkness is only scary when you stop moving.",
        "Don’t just survive — adapt so hard the pain gets confused.",
        "People say 'you’ve changed' like it’s an insult. Staying broken is worse.",
        "You get used to hell if you sit in it long enough.",
        "Nothing will ever feel different until *you* are different.",
        "You can scream silently for years. But nothing changes unless you stand up.",
        "The mind loves comfort. Even if it's killing you.",
        "Your excuses are smarter than you — stop feeding them.",
        "The worst cage is the one you decorated yourself.",
        "If you don’t rise, no one will notice your fall.",
        "Change isn’t hard. It’s horrifying. That’s why most people stay the same.",
        "You want a sign? Look in the mirror. That’s the only signal that matters.",
        "You weren't born with chains — you picked them up piece by piece.",
        "You already know what you need to do. You just won’t admit it yet.",
        "If rock bottom feels like home, it’s time to move.",
        "Every ignored emotion becomes a landmine later.",
        "If your dreams scare you, good. They should.",
        "No one is judging you more than you already are.",
        "You fear failure, but you're living it by not trying.",
        "Some people never leave their dark rooms. Don't be one of them.",
        "Your patterns are louder than your promises.",
        "You don't heal by reading quotes. You heal by doing the hard, boring work.",
        "The longer you hide, the more real the monsters feel.",
        "People don’t need to understand your pain. You just need to rise anyway.",
        "Your peace will cost you everything that isn’t real.",
        "You don't need hope. You need a ruthless plan.",
        "Success doesn’t care how sad you are. Only if you showed up.",
        "You can't medicate your way out of a lifestyle that breeds misery.",
        "You weren’t made to be small. But shrinking feels safer.",
        "Every minute you scroll for escape is a minute your future dies.",
        "You're not a mess — you’re avoiding the cleanup.",
        "You don’t lack energy. You waste it on things that drain you.",
        "That emptiness you feel? It’s not depression — it’s the call to evolve.",
        "Waiting for motivation is a losing game. Get up anyway.",
        "The world is brutal. But so are you — if you remember.",
        "You either become the architect of your mind or the prisoner of it.",
        "If you’re not fighting, you’re surrendering. And no one wins in silence.",
        "Your potential didn’t disappear. You buried it under fear.",
        "You are your habits, not your intentions.",
        "Your healing hurts because you’ve gotten used to bleeding.",
        "Stop worshipping your pain. It isn’t holy.",
        "No breakthrough ever came without breaking something first.",
        "It’s not the darkness that scares you — it’s the possibility of light.",
        "Your future self is begging you to move. Don’t ignore them.",
        "Nothing changes if you keep comforting your demons.",
        "The truth won’t kill you — but the denial might.",
        "If your survival became your prison, it’s time to escape.",
        "The world doesn’t want your pain — it wants your transformation.",
        "Let your past be fuel, not a leash.",
        "Your sadness is loud. But your silence screams louder.",
        "If you don’t face it, you’ll repeat it. Over and over.",
        "You can’t outrun yourself. So stop running and rebuild.",
        "The only real therapy is honesty — even if it hurts.",
        "You either become immune to excuses or enslaved by them.",
        "If you don’t rewrite your story, your past will be the author forever.",
        "You weren’t supposed to be normal. You were supposed to be unstoppable.",
        "Everyone is drowning in something. What matters is who swims anyway.",
        "Stop asking why it’s hard. Ask why you haven’t adapted.",
        "Your downfall began the moment you stopped being curious about yourself.",
        "You can be depressed *and* disciplined. That’s where healing starts.",
        "Don’t die a spectator of your own life.",
        "Your mind isn’t fragile — it’s just misused.",
        "Stop feeding pain with passivity.",
        "Your fear of change is stronger than your desire to grow. That’s the problem.",
        "You have a thousand chances. You waste them all waiting to feel 'ready'.",
        "You’re not a victim of your thoughts. You’re just scared to fight them.",
        "That darkness inside? It’s waiting to be turned into power.",
        "There’s nothing noble about staying broken.",
        "Your story doesn’t need sympathy. It needs action.",
        "Life doesn’t pause because you’re hurting. It just keeps scoring points.",
        "If you don’t like your reflection, change what cast the shadow.",
        "You weren’t born weak. You just stopped flexing your will.",
        "The mind is a battlefield. Win or decay — those are the only outcomes.",
        "You either discipline your pain or it disciplines you.",
        "Stop waiting for peace in a war you won't fight.",
        "Your pain has already cost you enough. Don’t let it bankrupt your future.",
        "The truth is ugly. That’s why it works.",
        "You will never grow in comfort. Only in pressure.",
        "The world doesn't care about your intentions — only your actions.",
        "You have the scars of a warrior. Act like it.",
        "You weren’t made to be hidden. You were forged in fire to rise.",
        "Stop playing victim in a game you refuse to leave.",
        "Your healing starts the moment your excuses end.",
        "If you’re not climbing, you’re sinking.",
        "Every time you give in to your pain, it gets stronger. So do something else.",
        "You want out? Then break the cycle. Even if it bleeds.",
        "You either starve your demons, or they eat you alive.",
        "You are the problem. And that’s the good news — because it means you’re also the solution.",
        "You’re not trapped — you’re just comfortable in your cage.",
        "No one can hear you if you keep whispering into the void.",
        "You weren't born to quit. You just forgot how to fight.",
        "The dark doesn’t win. You just stopped lighting matches.",
        "You are not your lowest moment — unless you stay there.",
        "A new life costs the death of your current one. Pay up.",
        "If nothing changes, nothing heals.",
        "Wake up — your time isn’t infinite, but your excuses are.",
        "Every day you stay the same, something inside you dies quietly.",
        "Stop making sadness your identity. You were meant for more.",
        "You are more dangerous than your depression — if you choose to be.",
        "Nothing grows in darkness — unless it decides to become the light.",
        "If you don’t save yourself, no one will.",
        "You don’t need closure. You need clarity and action.",
        "The most powerful people aren't the happiest — they’re the ones who keep going anyway.",
        "Healing is war. And you’ve been unarmed for too long.",
        "This pain isn’t your identity — it’s your invitation.",
        "Stop negotiating with your fears. Dominate them.",
        "You’re wasting miracles waiting for motivation.",
        "That fire inside you? Use it. Or it’ll burn you from within.",
        "There is no hero coming. You *are* the hero. Now act like it."
    ],
    more: [
        "The mind won’t shut up, so you have to move anyway.",
        "If waiting for motivation worked, you’d be a billionaire by now.",
        "Your thoughts lie. Your actions don’t.",
        "You’re not stuck. You’re hesitating in fear, disguised as overthinking.",
        "Start before you're ready, because 'ready' is a myth your brain created.",
        "Thinking about working isn’t working.",
        "Nothing changes if nothing moves.",
        "You want silence in the head? Create noise in the world.",
        "Confusion ends where movement starts.",
        "Your mind’s not the enemy. Inaction is.",
        "You can’t escape the mental storm, but you can walk through it.",
        "Overthinking is mental masturbation. Feels busy, does nothing.",
        "You already know what to do. You’re just hoping for an easier answer.",
        "Silence the spiral by doing the first damn thing.",
        "Discipline is loyalty to your future self, not your current mood.",
        "Action kills fear. Inaction feeds it.",
        "Your brain’s chaos is a symptom. The cure is routine.",
        "Stop negotiating with your mind. It doesn't want growth — just comfort.",
        "You’re not broken. You’re bored and overstimulated.",
        "Get uncomfortable or stay the same — no one’s coming to save you.",
        "You can either wrestle with your mind or redirect it. Only one moves you forward.",
        "Clarity comes after action, never before.",
        "Work now. Cry later. Rest later. Heal later. Move *now*.",
        "Fear of failure is a delay tactic. So is perfectionism.",
        "If it’s hard to start, it means it matters.",
        "The only way to feel better is to become the person who does the thing anyway.",
        "Even 10 minutes of focus is a rebellion against your own limits.",
        "You’re not lazy. You’re drowning in a mind that won’t shut up. Swim anyway.",
        "Thoughts race. You pace. Pick the pace.",
        "Waiting for clarity is a trap. Build it by doing.",
        "No one’s coming to fight your mind. You’ll have to do it alone.",
        "If you're stuck in thought, you're not in life.",
        "Start ugly. Start tired. Start anxious. But start.",
        "Productivity isn’t a mood. It’s a choice repeated enough to become a habit.",
        "You think you need peace first. You need progress first.",
        "The longer you wait, the heavier it feels.",
        "Small actions are louder than loud intentions.",
        "It’s not your fault you're struggling. But it is your job to fight through.",
        "Mental fog lifts when motion begins.",
        "Even if your mind roars, your hands can still move.",
        "Focus is a muscle. Train it with friction.",
        "Let your frustration build into a weapon, not a wall.",
        "You want a better headspace? Build a better habit.",
        "Panic is loud. Progress whispers. Listen closer.",
        "Get out of your head. Into your body. Do the work.",
        "You don’t need a plan. You need to move.",
        "Stop trying to figure out how to feel better. Do something.",
        "The first five minutes are hell. The rest is momentum.",
        "You’re one step away from proving your mind wrong.",
        "Stop thinking. Start sweating.",
        "Fear is a liar. Results are proof.",
        "Your thoughts are chaos. Build order with action.",
        "Tired of thinking? Do. That’s the cure.",
        "You’re not your mind. You’re what you do despite it.",
        "There’s no perfect state. Only now. Use it.",
        "Burnout feels like chaos. But clarity hides in structure.",
        "Your excuses wear different masks. Tear them all off.",
        "You don’t need to feel it. You need to finish it.",
        "No amount of thinking substitutes for 10 minutes of doing.",
        "The mind spirals. You ground it with grit.",
        "Don’t wait to feel okay. Create okay by showing up.",
        "If your mind’s your worst enemy, treat action as self-defense.",
        "Stop babysitting your mood. Grow through it.",
        "You can either complain or conquer. Not both.",
        "You already know what’s eating you. Starve it with effort.",
        "Your brain’s tired because it’s untrained. Train it.",
        "Noise in the head? Mute it with noise in the world.",
        "One task. One breath. One win.",
        "Nobody sees how loud your head is — only what you did anyway.",
        "The answer is not rest. It’s rhythm.",
        "You don’t need peace of mind to win. You need war with laziness.",
        "One action today murders 100 regrets tomorrow.",
        "Your thoughts won’t stop for you. So step *through* them.",
        "Don’t trust a mind trained in fear.",
        "If the task scares you, it’s worth it.",
        "Think less. Bleed more (sweat counts).",
        "Energy comes after action. Not before.",
        "You’re drowning in potential and afraid of swimming.",
        "The brain won’t agree. That’s fine. It follows the body.",
        "One focused hour a day rewrites everything.",
        "Your life isn’t ruined. You’re just stuck on pause.",
        "Chaos is not your identity. It’s your test.",
        "Stop checking your thoughts. Start checking off tasks.",
        "You want self-worth? Earn it with daily rebellion against apathy.",
        "You’re not alone. You’re untrained. That can change.",
        "The mess in your head is just noise. Don’t obey it.",
        "Be your own savior. No one else will drag you to the finish line.",
        "The mind lies. The grind doesn’t.",
        "You’re not addicted to laziness. You’re terrified of trying.",
        "Escape the storm by walking — not by wishing.",
        "Motivation is a scam. Motion is real.",
        "You know the problem. Be the solution.",
        "Even progress through tears is still progress.",
        "Mind raging? Let your body lead the way.",
        "If thinking fixed it, you’d be healed already.",
        "Worry is a weak substitute for work.",
        "Your current mood doesn’t define your future moves.",
        "Get angry. Get up. Get it done.",
        "Do it not because you want to — but because *you refuse to stay the same.*",
        "Fear the regret of staying still more than the fear of moving wrong.",
        "Don’t wait to stop hurting. Work while it hurts.",
        "Even demons pause when discipline walks in.",
        "Be so consistent, even your depression can't keep up.",
        "Kill the old version of yourself. Bury it under effort.",
        "You feel like hell. Good. That means you’re alive. Use it.",
        "Self-pity is a cage. Kick the damn door open.",
        "You think your mind is unbeatable? Prove it wrong.",
        "You’re tired of this cycle? Then break it with violence — mental effort is violence.",
        "Your excuses are polished lies. Smash them with ugly effort.",
        "Can’t focus? Force it. You’re not a victim of your own head.",
        "The battlefield is your desk. Fight like something’s on the line — because it is.",
        "Your brain says no. Your future screams yes. Who are you listening to?",
        "You’ve waited enough. Now act like your life depends on it — because it *does.*",
        "No miracle is coming. Be the damn miracle.",
        "Don’t feel like it? Too bad. That never mattered anyway.",
        "Let your hands do the work your mind’s too afraid to start.",
        "The storm in your mind is no excuse. It’s a reason to move faster.",
        "You don't need clarity. You need war-mode.",
        "Break the loop. Break the pattern. Or break down. Your choice.",
        "The voices in your head are liars. Mute them with momentum.",
        "Stop asking your brain for permission. It’s the enemy now.",
        "You don't need healing. You need habits.",
        "If you hate your thoughts — drown them in results.",
        "Every second you sit still, your potential bleeds out.",
        "Nobody's coming. Nobody *cares* — so you better care enough to move.",
        "Make your inner demons regret picking you.",
        "If you're not angry at your inaction, you haven’t hit rock bottom yet.",
        "Let your suffering mean something. Turn it into scars that built a beast.",
        "Your comfort is your cage. Smash it with rage.",
        "You’re not sad. You’re sedated by excuses.",
        "You don’t need help. You need heat. Burn through this slump.",
        "Be your own executioner. Kill the weak version of you.",
        "Your laziness is louder than your dreams right now. Fix that.",
        "You're not a failure. You're a fighter who hasn't started swinging.",
        "Do it shaking. Do it crying. But do it *like hell depends on it.*"
    ],
    lonely: [
        "They don't support you because they can't handle your potential.",
        "Isolation isn't punishment. It's preparation.",
        "When you're too real, you become everyone's threat.",
        "The people who left weren't your loss. You were theirs.",
        "Silence speaks louder than fake praise.",
        "You're not alone. You're just surrounded by noise, not people.",
        "Sometimes solitude is the only honest place left.",
        "Being doubted is the greatest proof you're doing something right.",
        "They want you to fail because your success would expose their laziness.",
        "Loyalty fades fast when envy sets in.",
        "They smile while hoping you trip. Step harder.",
        "Your instincts weren’t wrong. You just didn’t want them to be right.",
        "Rejection is just redirection from cowards.",
        "They don’t support you because they secretly want to be you.",
        "You're not broken. You're just tired of carrying your own weight.",
        "If you feel alone, it's because you're finally becoming yourself.",
        "No one claps for the silent fighter. Clap for yourself.",
        "People fear what they can’t control. That’s why they fear you.",
        "Your pain isn't weakness. It's your blueprint.",
        "Loneliness teaches you the names of your fake friends.",
        "They won’t help you win — but they’ll show up to watch you lose.",
        "Some betrayals hit harder because we expected better from trash.",
        "You're not losing your mind. You're just shedding your illusions.",
        "Your trust issues saved you more than you know.",
        "People fear the version of you that doesn’t need them.",
        "The fewer people you trust, the safer your peace becomes.",
        "They laughed at your struggle — remember that when you rise.",
        "It’s not that they want you to lose. It’s that they *need* you to.",
        "They don't stab you in the back. They wait for you to heal, then do it again.",
        "Being used feels like love until you realize what real love is.",
        "When you're alone, you're finally out of reach of their poison.",
        "No one supports a storm until it becomes a hurricane.",
        "Trusting people blindly is the fastest way to blind yourself.",
        "The ones who disappear during your darkest hours were never light to begin with.",
        "If they wanted to help, they would’ve. Remember that.",
        "When support is conditional, it's not support — it's manipulation.",
        "Your power lies in how many times you stood alone and didn’t fold.",
        "They love when you need them. They hate when you don't.",
        "Trusting no one doesn’t make you bitter. It makes you honest.",
        "They won't clap for you, because your growth exposes their excuses.",
        "Be thankful they left. They would've killed your light slowly.",
        "Your enemies wear smiles. Your allies wear silence.",
        "Keep your circle tight. Or better — be the whole damn shape yourself.",
        "No one checks on the strong. That’s how the strong are made.",
        "Your solitude is more loyal than most people.",
        "When people can’t destroy you, they’ll try to isolate you.",
        "Most people don’t leave you. They reveal themselves.",
        "Your gut feeling is your guardian. Stop ignoring it.",
        "Betrayal doesn’t require swords — just silence when you’re bleeding.",
        "The loner isn’t the weakest. He’s just the only one who sees the truth.",
        "They don’t understand you because they never tried.",
        "Let them doubt. You were never built for their comfort.",
        "If no one has your back, turn your pain into wings.",
        "You don’t need validation from the same mouths that pray for your failure.",
        "If they wanted to see you win, they’d help you build.",
        "Tough days don’t mean you’re failing. They mean you’re resisting collapse.",
        "Sometimes survival looks like silence and scars.",
        "People will drain your soul and call you dramatic when you scream.",
        "You were loyal to snakes. Forgive yourself, not them.",
        "Every betrayal taught you how to build armor.",
        "They want your silence because your truth is louder than their lies.",
        "Never expect depth from puddles.",
        "You never needed them. You just forgot how strong you were.",
        "Your comeback will make their hate irrelevant.",
        "Not everyone around you wants peace — some feed off your chaos.",
        "It’s okay to outgrow the people you once cried for.",
        "Being real is the fastest way to lose fake people.",
        "Your loneliness is your rebirth, not your end.",
        "Let them call you cold — at least you stopped burning for others.",
        "You're the villain in their story because you stopped being the victim.",
        "If you weren't powerful, they wouldn’t try so hard to dim you.",
        "They didn’t want you to win — just close enough to watch you fail.",
        "Fake support sounds like silence when you scream.",
        "The more you love yourself, the less they control you.",
        "Your solitude is a revolution.",
        "You're not too much. They're just not enough.",
        "Walk alone. It's better than walking with betrayal.",
        "Don’t expect loyalty from those who envy your soul.",
        "They didn't leave you behind. You just outgrew their cages.",
        "Some people only come close enough to study your weakness.",
        "When no one believes in you, let that be your fire.",
        "You were never hard to love. They were just incapable.",
        "Stay dangerous. Kindness without boundaries is self-destruction.",
        "Learn to be your own rescue plan.",
        "Trust is earned. Keep your doors locked until then.",
        "Never fear being alone. Fear needing the wrong people.",
        "Every time they counted you out, they made you count more.",
        "People disappear when you stop breaking for them.",
        "You didn’t lose people. You lost burdens.",
        "Not all family is blood. Some blood is poison.",
        "Solitude is where warriors recharge.",
        "You're not paranoid. You’ve just seen too much to stay blind.",
        "Those who left you are the weight you were meant to drop.",
        "Let them gossip. Wolves don’t concern themselves with sheep chatter.",
        "You survived them once. You’ll do it again, louder.",
        "The loner isn’t broken. He’s just tired of liars.",
        "You're not too broken to be loved. Just too real to be used.",
        "Your isolation is where your empire begins.",
        "One day, you’ll thank the pain for shaping the weapon you became.",
        "When no one believes in you, be the believer you never had.",
        "Walk silent. Build heavy. Hit loud.",
        "Being doubted is a gift. It makes your success louder.",
        "They want you weak because it comforts their failure.",
        "They ghosted you because your light blinded their lies.",
        "You're not a mistake. You’re a mirror they can’t face.",
        "Let them underestimate you — it’ll make the roar louder.",
        "Watch how they hate when you heal without them.",
        "Your darkness isn’t evil. It’s armor.",
        "Being alone didn’t break you. Trusting the wrong ones did.",
        "You're your only real ally. Sharpen that truth.",
        "People fear what they can’t manipulate.",
        "Your pain is your proof. Wear it like a crown.",
        "They hate your strength because it reminds them of their cowardice.",
        "You don’t need closure. You need boundaries.",
        "Betrayal is the tax of being valuable.",
        "You were chosen to walk alone — because crowds can't handle fire.",
        "Your trauma didn't destroy you. It forged you.",
        "The silence they left behind is where your empire echoes.",
        "Let them watch. You're the storm they whispered about.",
        "They didn’t break you. They just freed the monster in you.",
        "Real strength is bleeding silently while building wildly.",
        "The more they hate, the more you're becoming.",
        "You're alone because the world is too soft for your intensity.",
        "They don’t support you because your victory ruins their narrative.",
        "No one cares until you’re gone. Let them mourn your silence.",
        "Stop seeking loyalty in graves full of betrayal.",
        "People love you broken. They fear you healed.",
        "Let their absence remind you why they were never real.",
        "You were the light. They were just scared of fire.",
        "You don’t trust people because your scars remember better.",
        "Stop saving people who enjoy watching you drown.",
        "They want your fire — not your warmth. Burn them away.",
        "Your worst mistake was thinking they cared.",
        "Let them choke on the silence they left you in.",
        "You weren’t abandoned. You were upgraded.",
        "They left when your wounds no longer bled for them.",
        "Fake love sounds sweet but tastes like poison.",
        "Your existence offends cowards. Good.",
        "Don’t expect snakes to grow spines.",
        "They want access to your growth without watering your soul.",
        "You’re the villain in their story because you dared to heal.",
        "Let them miss you in their misery.",
        "If no one claps, burn the stage and build your own arena.",
        "Your loyalty was their weapon. Turn it into your shield.",
        "You didn't lose them. You woke up.",
        "Their support dies the second you stop needing it.",
        "You're hated because you refused to crawl.",
        "They don’t love you. They love controlling you.",
        "Be the ghost in their mirror.",
        "Stop explaining storms to those who drown in puddles.",
        "They killed your trust. Now let it haunt them.",
        "You trusted clowns and expected kings.",
        "You weren’t too much. They were too fake.",
        "Stop feeding wolves who bit the hand that saved them.",
        "If betrayal was a knife, you'd be a swordsmith by now.",
        "They cheered your silence. Now scream success in their face.",
        "Trust is earned. Not demanded by parasites.",
        "Your fall was planned. Make your rise a massacre.",
        "Let the traitors talk. Their voices rot in truth.",
        "Loyalty is rare. So is your peace. Guard both with teeth.",
        "You don’t need more friends. You need fewer liars.",
        "Your silence is revenge they can’t block.",
        "You owe them nothing. Not even your hate.",
        "Stop forgiving vipers.",
        "You were their last bite. Now they starve.",
        "If you're hated for being real, double down.",
        "They lost you the moment they tested your silence.",
        "You don’t need a hug. You need a sword.",
        "Let them think you’re cold. You’ve just buried too many fake flames.",
        "The best revenge? Existing louder than their absence.",
        "You trusted shadows. Now become the darkness they fear.",
        "You're not alone. You're just finally with someone who never lied — yourself."
    ],
    better: [
        "You don’t need more time. You need fewer excuses.",
        "No one is coming to save you. Get up.",
        "Every second you waste becomes part of the regret you'll carry.",
        "You say you want better, but your habits say otherwise.",
        "Better isn’t found. It’s built. Daily. In silence. With blood.",
        "Your potential means nothing if you're too lazy to use it.",
        "Comfort is a cage disguised as peace.",
        "Discipline is self-respect in action.",
        "You’re not stuck. You’re scared of effort.",
        "Wanting better won’t get you better. Working will.",
        "Excuses build nothing but regret.",
        "Growth hurts. But staying the same destroys.",
        "The pain of improvement is temporary. Regret is forever.",
        "There’s no shortcut. There’s just showing up daily.",
        "You aren’t tired. You’re undisciplined.",
        "Your goals are waiting on the other side of your laziness.",
        "Fear is loud. Action is louder.",
        "Stop expecting success with average effort.",
        "Don’t wait for motivation. Build discipline.",
        "Someday is a lie you tell yourself daily.",
        "The more you delay, the more you decay.",
        "Your standards decide your future.",
        "You won’t always be motivated. Learn to be consistent.",
        "If it’s important, act like it.",
        "There is no 'ready'. Only 'start'.",
        "Your comfort zone is your kill zone.",
        "Decide: Do you want ease or excellence?",
        "Improvement feels like pain at first. Then it becomes power.",
        "You aren’t overwhelmed. You’re just avoiding effort.",
        "The world doesn’t wait for your excuses.",
        "Progress is quiet. So is failure.",
        "You either discipline yourself or destroy your potential.",
        "Doing nothing is still a decision. A bad one.",
        "Quit complaining. Start evolving.",
        "Your future self is begging you to move.",
        "Focus beats talent every time.",
        "Don’t measure time. Measure effort.",
        "The price of success is discomfort.",
        "Stop scrolling. Start building.",
        "No one cares about your 'almost'.",
        "A better life won’t knock. Build the damn door.",
        "You dream like a lion. You work like a snail.",
        "Action makes belief stronger. Not the other way around.",
        "You either suffer the pain of growth or stay broken.",
        "Inconsistency kills more dreams than failure ever could.",
        "Your daily choices are shaping your legacy.",
        "Start acting like your life depends on it — because it does.",
        "Hope won’t help you. Habits will.",
        "Sleep on your goals, and you’ll wake up with regrets.",
        "Hard truth: No one owes you progress.",
        "You’re not behind. You’re just not doing the damn work.",
        "You don’t need better circumstances. You need better consistency.",
        "Change doesn’t come from thinking. It comes from doing.",
        "You can't Netflix your way into a better life.",
        "Stop hiding behind potential. Use it.",
        "You said 'next time' last time too.",
        "Focus isn’t found. It’s forced.",
        "Tough times don’t make you weak. Laziness does.",
        "Want change? Kill your comfort first.",
        "The grind doesn’t care how you feel today.",
        "The gap between average and excellent is daily discipline.",
        "You don’t rise to goals. You fall to your systems.",
        "Quit hoping for it. Hustle for it.",
        "You can’t cry your way into improvement.",
        "That voice saying 'you can't' is just lazy logic.",
        "Shut up. Get up. Show up.",
        "If it was easy, you wouldn’t respect it.",
        "Your distractions are stronger than your dreams.",
        "You don’t need a miracle. You need momentum.",
        "Even failure teaches. Doing nothing teaches nothing.",
        "You have the time. You’re just wasting it.",
        "Excuses are exits from excellence.",
        "Your actions are the real résumé of your character.",
        "The truth? You can. You just won’t.",
        "Wake up. Nobody’s coming. Build yourself.",
        "You're not overwhelmed. You're underfocused.",
        "Start ugly. Start small. But start.",
        "Your potential is dying inside your comfort zone.",
        "Effort never lies.",
        "Today’s pain is tomorrow’s pride.",
        "One more excuse = one less result.",
        "You can either feel the burn now or regret forever.",
        "Your best version is buried under your worst habits.",
        "Change is lonely. But so is staying average.",
        "A better life isn’t built with comfort.",
        "Stop thinking. Start sweating.",
        "No progress happens without pressure.",
        "You don’t need to feel ready. You need to move.",
        "Success is rented daily — and rent is due now.",
        "You want results? Do what most won’t.",
        "Get tired of your own nonsense.",
        "Work until your doubts shut up.",
        "Talent sleeps. Effort doesn’t.",
        "The longer you wait, the heavier regret gets.",
        "Even slow steps count — but they require you to move.",
        "You’re drowning in comfort.",
        "Don’t expect success with lazy effort.",
        "Push through the pain. That’s where growth lives.",
        "Average is crowded. Be allergic to it.",
        "Comfort kills more dreams than failure ever will.",
        "If you don’t feel like it, that’s the best time to do it.",
        "You say you’ll try. That’s why you fail.",
        "Success isn’t sexy. It’s consistency when no one claps.",
        "You know what to do. You’re just not doing it.",
        "Nobody can save you from the work you refuse to do.",
        "Every excuse you make builds your own cage.",
        "Discipline > Drama.",
        "Motivation fades. Muscle memory of effort doesn’t.",
        "You can either evolve or repeat. Your choice.",
        "Don’t fear failure. Fear being in the same place next year.",
        "If you want it bad, act like it.",
        "Staying the same is more dangerous than failing.",
        "One day or day one — you choose.",
        "You aren’t too late. You’re just too lazy.",
        "Your comfort zone wants to kill your ambition.",
        "There’s no glory in giving up quietly.",
        "Quit the fantasy. Do the work.",
        "Be addicted to effort, not excuses.",
        "You can’t win if you’re not in motion.",
        "Avoiding the hard path? Avoiding the results too.",
        "Time isn’t your enemy. Your inaction is.",
        "You’ve been waiting on the 'right time' to waste more time.",
        "Stop being a slave to your excuses.",
        "Want to improve? Sacrifice something. Start with your comfort.",
        "You're either growing or rotting. There's no idle.",
        "Half effort, half results. Always.",
        "The clock won’t stop because you’re tired.",
        "Your competition’s working while you’re whining.",
        "You don’t need motivation. You need consequences.",
        "Get serious or get used to average.",
        "No one’s impressed by what you almost did.",
        "You can’t hack hard work. Ever.",
        "You’re not owed a result. You owe the grind.",
        "If it’s hard, good. Most won’t do it.",
        "Be so relentless even your doubts quit.",
        "The longer you wait, the further you fall behind.",
        "If you’re not hungry, someone else is — and they’re coming.",
        "Lazy dreams breed bitter people.",
        "No one applauds mediocrity. Don’t live there.",
        "You’re not tired. You’re untrained.",
        "Feel like quitting? That’s when winners begin.",
        "Regret is forever. Pain is temporary.",
        "You’re losing to yourself. Every. Damn. Day.",
        "Being soft is a luxury you can’t afford.",
        "Nobody’s holding you back but your weak mindset.",
        "You want better? Then stop acting average.",
        "Quit hoping for miracles. Start becoming one.",
        "That ‘someday’ mindset is murdering your future.",
        "Nobody respects 'almost'. They remember results.",
        "You’re training your brain to be okay with mediocrity.",
        "If you're not moving, you're decaying.",
        "There’s no prize for planning forever. Start.",
        "You talk about discipline. But fold under pressure.",
        "Want results? Then kill your excuses. Ruthlessly.",
        "One hour of real work beats days of fake intentions.",
        "You can't be a beast with a sheep mindset.",
        "Don't be shocked when life doesn't reward your laziness.",
        "You can't keep choosing easy and expect extraordinary.",
        "Every lazy decision builds your failure brick by brick.",
        "The mirror shows your real enemy. Now fight it.",
        "Burn your comfort zone to the ground.",
        "You deserve better — but only if you *earn* it.",
        "Soft efforts make soft results. Harden up.",
        "You failed today? Good. Now do better tomorrow.",
        "You have no excuse left. Only fear.",
        "If you're not obsessed with progress, you're settling for scraps.",
        "Weakness is loud. Discipline whispers.",
        "You're either the reason you rise or the excuse you stay broken.",
        "You're not failing. You're choosing comfort over growth.",
        "Hustle like your life depends on it — because it does."
    ],
    hope: [
        "Rock bottom isn’t the end. It’s the foundation where real ones rebuild.",
        "Hope isn’t a light that finds you. It’s the fire you build with broken pieces.",
        "Sometimes life doesn’t throw you a rope. You have to climb out with bleeding hands.",
        "Your story doesn’t end in darkness—unless you stop writing.",
        "Even dead stars still light up the night. What’s your excuse?",
        "When you feel like giving up, remember—your demons do too. They fear your rise.",
        "Hope isn’t for the lucky. It’s for the stubborn.",
        "You’ve already survived 100% of your worst days. That’s not failure. That’s proof.",
        "You don’t have to believe in the sunrise. It’ll show up anyway. So should you.",
        "Hell is just a stop. Not your destination.",
        "The darkest moments test your right to shine. Claim it anyway.",
        "When hope is gone, become the kind of person even hope would return for.",
        "You’re not lost—you’re just not done evolving yet.",
        "Your mind is a battlefield. Hope is the rebellion.",
        "You weren’t born to break. You were built to bend and bounce back.",
        "Hope isn’t soft. It’s the sharp edge that cuts through despair.",
        "A spark in pitch black is brighter than sunlight. Be that spark.",
        "You don’t need a miracle. You need motion.",
        "If no one believes in you, good. That makes your success terrifying.",
        "Hope won’t knock. Sometimes you have to break your own door down.",
        "The ground didn’t swallow you. So stand up.",
        "You’re here. That means the universe hasn’t finished with you yet.",
        "The fact you’re breathing is your second chance—every second.",
        "You are the weapon forged by suffering.",
        "Don’t wait for a light. Become the matchstick.",
        "Hope is a muscle. It grows when it’s torn.",
        "The void looks back, but it’s afraid of you.",
        "If life kicked you down, use the ground to push up.",
        "Monsters don’t hide under beds. They grow inside. But so does the hero.",
        "Stop begging for a break. Break through.",
        "No one escapes storms. Some just learn to become the thunder.",
        "Darkness isn’t meant to break you. It’s meant to reveal what you’re made of.",
        "Hope isn't naive. It's the ultimate rebellion.",
        "You're not running out of time. You're running out of excuses.",
        "A broken past isn’t a curse. It’s armor.",
        "If they buried you, good. That’s where seeds start.",
        "Even ashes remember how to burn.",
        "Strength isn’t loud. Sometimes it’s just not giving up.",
        "Scars are receipts. They prove you paid the price and lived.",
        "Every sunrise you ignore still comes for you. Start returning the favor.",
        "You’ve been fighting so long, you forgot—you’ve already won so many rounds.",
        "Dead ends are places to turn, not stop.",
        "You are the glitch in fate’s plan. Make it crash.",
        "Hope is forged in silence, not shouted in peace.",
        "The mirror lies. Your fight doesn’t.",
        "If you think you’ve hit the end, look again—it might just be a bend.",
        "You’re not too broken. You’re battle-tested.",
        "Even cracked steel cuts deep.",
        "If you're tired of falling—build wings from your bruises.",
        "Despair isn't final. It’s just loud.",
        "You survived your worst days. What’s today going to do to you?",
        "The dark didn’t win. You’re still breathing.",
        "Hope isn’t cute. It’s chaos wrapped in belief.",
        "The weight you carry isn’t weakness. It’s your proof.",
        "When all else fails, drag yourself forward. Crawl if you must.",
        "You were made from stars, not dust alone.",
        "Breakdowns are how breakthroughs are born.",
        "Every 'I can't' you say is a lie fear told you.",
        "You're not hopeless. You’re healing.",
        "The night doesn’t last forever. But you do.",
        "Let the silence shape you, not swallow you.",
        "Your mind is brutal—but you’re still in control.",
        "Hope is dangerous—and that’s what makes it worth it.",
        "You were not built to be understood by the weak.",
        "You don't need saving. You need remembering who the hell you are.",
        "Your worst days built walls. Now turn them into stairs.",
        "Pain is a teacher. Listen. Then outgrow it.",
        "A single step in the dark still breaks the darkness.",
        "The future doesn’t care if you’re ready. It’s coming anyway. Meet it screaming.",
        "You're the reason fear wakes up worried.",
        "You've already fought battles that would've crushed others.",
        "There’s a reason you didn’t break. That reason is you.",
        "You have no idea how much chaos you're meant to survive and conquer.",
        "The edge is not your end—it’s where wings spread.",
        "Don’t aim to be okay. Aim to be unstoppable.",
        "Hope is not light. It's fire. Burn back.",
        "What haunts you fears your comeback.",
        "If life gave you hell, it’s because you were meant to walk through it and return crowned.",
        "You may feel hollow, but even that emptiness has room for power.",
        "Let pain push you until purpose pulls you.",
        "You can’t be lost when you’re still moving.",
        "Fear is a liar. And it talks the loudest before you win.",
        "Your silence is not your weakness. It’s your reload.",
        "You’re not broken. You’re becoming.",
        "There’s still a version of you that makes it. Become them.",
        "Your demons? They scream because they know what you’re capable of.",
        "You are the storm your fears dread.",
        "Don't try to feel better. Try to get stronger.",
        "Being numb is not giving up. It’s your mind saving your soul until you’re ready again.",
        "If the dark didn’t kill you, what makes you think the light won’t rebuild you?",
        "You’ve died before—emotionally. And look. You’re still here.",
        "Nothing’s coming to save you. Be your own rescue.",
        "Each breath you take is defiance. Keep breathing.",
        "Comfort is the killer of growth. Good. Let pain shape you.",
        "You think you're alone. But even shadows need a light source.",
        "That crack in your armor? That’s where your fight shines through.",
        "You don’t need a reason to hope. You need guts to dare.",
        "The mountain doesn’t move. You climb it or conquer it. No in-between.",
        "Your past is not your prison. It’s your proof.",
        "Don’t romanticize hope. Weaponize it.",
        "Fear hates consistency. Be relentless.",
        "You’re not fragile. You’re forged.",
        "The fall is loud. But rising is louder in silence.",
        "Your heart still beats. That’s a declaration of war.",
        "Don't chase light. Become it.",
        "You've walked through hell. Dance in its ashes.",
        "If you've ever cried and stood back up, you already won.",
        "Nothing is harder than continuing. That’s why it matters.",
        "Your shadow only proves you haven’t been consumed.",
        "Don't look for signs. Be one.",
        "No path? Burn one through.",
        "You're the glitch the system can't handle.",
        "Some days you survive. Some days you conquer. Both count.",
        "You didn’t come this far to kneel.",
        "What if your comeback is meant to be terrifying?",
        "Don’t die with potential in your veins. Spill it out into reality.",
        "If your hope is shaking, let it shake. Then anchor it with will.",
        "You don't need to rise perfect. Just rise.",
        "Your bloodline made warriors. You're next in line.",
        "If the world gave up on you, good. That means no one’s watching while you win.",
        "You are not your pain. You’re the one who survived it.",
        "The fight isn’t over. But neither are you.",
        "You weren’t meant to fit in. You were built to break out.",
        "There’s fire in you still. Let it burn something down.",
        "Even ruins make good homes. Rebuild.",
        "It’s not over until your breath stops. And even then, legends rise.",
        "Fall seven times. Stand the hell up eight.",
        "Every day you choose not to disappear is defiance.",
        "They’ll regret underestimating the one who kept standing.",
        "Hope won’t help you if you stay on your knees. Get up or get used to the dirt.",
        "No one's coming. Get up anyway.",
        "You're not tired. You’re undisciplined. Train your will.",
        "Feelings are liars. Actions are truth. Choose truth.",
        "The world doesn’t owe you hope. Steal it back.",
        "Stop wishing. Start bleeding for it.",
        "If you want peace, earn it through pain.",
        "You're not fragile. You're just afraid to admit you're strong.",
        "Excuses are lies fear tells when it's losing.",
        "Hope is earned, not handed.",
        "You’re not drowning. You’re refusing to swim.",
        "Comfort is where dreams rot.",
        "Hope is for fighters. Are you one?",
        "Stop holding your breath and calling it patience.",
        "You either break the cycle or become the reason it continues.",
        "Life owes you nothing. Take everything.",
        "Soft people don’t survive storms. Be the storm.",
        "You say you're done? Then stay down. Or shut up and rise.",
        "You want change? Suffer for it.",
        "Rock bottom is cozy if you stay too long.",
        "You hate your life? Then do something, not cry about it.",
        "If you can scroll, you can fight.",
        "Tears won’t fix it. Action will.",
        "Get tired of your own excuses.",
        "Wishing for hope is just glorified waiting.",
        "You’re not weak. You’re lazy with your power.",
        "Pain isn’t punishment. It’s a forge.",
        "Hope without action is useless fiction.",
        "No more pity. Only progress.",
        "You didn’t lose. You stopped.",
        "Either build your path or be crushed under someone else's.",
        "Hope screams when pushed. Are you listening?",
        "Weakness isn't feeling pain. It's staying in it on purpose.",
        "No battle is won in comfort.",
        "You wanted strength? Then why are you afraid to struggle?",
        "Every excuse buys you failure in full.",
        "Darkness isn't the enemy. Inaction is.",
        "Feel the fear. Then punch through it.",
        "Nobody cares how you feel—until you win.",
        "There’s no rescue. Only rage and rebuild.",
        "Waiting for motivation? Keep waiting. Winners start without it.",
        "Shut down the whining. Switch on the war.",
        "Stop calling your surrender peace.",
        "If you don’t fight back, you already lost.",
        "Wishing won't win wars. Will does.",
        "Hope doesn't live in the heart. It lives in the grind.",
        "You’ve suffered enough. Now suffer forward.",
        "You don’t need a second chance. You need to use the first one right.",
        "Silence the victim in you. Awaken the villain to your fears.",
        "Pain is your currency. Spend it wisely.",
        "Enough crying. Build the monster they fear.",
    ]
  };
  
  function showQuote(feeling) {
    const quoteBox = document.getElementById('quoteBox');
    const selectedQuotes = quotes[feeling];
    const randomIndex = Math.floor(Math.random() * selectedQuotes.length);
    const quote = selectedQuotes[randomIndex];
  
    quoteBox.innerHTML = `
      <div style="opacity: 0.8; font-size: 0.95em; margin-bottom: 6px;">All I gotta tell you is —</div>
      <div style="font-size: 1.3em; font-style: italic; margin: 8px 0;">“${quote}”</div>
      <div style="opacity: 0.7; font-size: 0.9em; margin-top: 6px;">It’s on you, bro.</div>
    `;
  }
  